#!/usr/bin/env sh

timeout=10
sleeptime=1

testcases='m3ua-asp-aspsm-v-002
           m3ua-asp-aspsm-i-001
           m3ua-asp-aspsm-i-003
           m3ua-asp-aspsm-o-001
           m3ua-asp-aspsm-o-002
           m3ua-asp-asptm-v-001
           m3ua-asp-asptm-v-008
           m3ua-asp-asptm-i-003
           m3ua-asp-asptm-o-001
           m3ua-asp-mtr-i-002'

for testcase in $testcases
do
  ./runm3uatest -d . -t $timeout $testcase 2> /dev/null
  sleep $sleeptime
done
