#!/usr/bin/env sh

timeout=10
sleeptime=1

testcases='m3ua-sgp-aspsm-v-003
           m3ua-sgp-aspsm-i-001
           m3ua-sgp-aspsm-i-002
           m3ua-sgp-aspsm-i-003
           m3ua-sgp-aspsm-o-001
           m3ua-sgp-asptm-v-003
           m3ua-sgp-asptm-v-008
           m3ua-sgp-asptm-v-011
           m3ua-sgp-asptm-i-004
           m3ua-sgp-asptm-o-001'

for testcase in $testcases
do
  ./runm3uatest -d . -t $timeout $testcase 2> /dev/null
  sleep $sleeptime
done
